#!/bin/bash
#/usr/bin/cmake /mnt/sata0/095e863dc1963676775f48e85c5e33a0/output/build/armada7k-aarch64/sysha-1.0.0/ -DCMAKE_TOOLCHAIN_FILE="/mnt/sata0/095e863dc1963676775f48e85c5e33a0/output/host/armada7k-aarch64/share/buildroot/toolchainfile.cmake" -DCMAKE_INSTALL_PREFIX="/usr" -DCMAKE_COLOR_MAKEFILE=OFF -DBUILD_DOC=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLE=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TEST=OFF -DBUILD_TESTS=OFF -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON  -DBUILD_WITH_NTOS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON )
cmake -S . -B build/ \
    -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake \
    -DBUILD_WITH_NTOS=ON \
    -DCMAKE_BUILD_TYPE=Debug \
    -DBUILD_TESTING=ON

